In [34]:
# Importando bibliotecas
import pandas as pd
from datetime import datetime
from datetime import timedelta

# Adiciona nova linha no DataFrame principal
def addRow(base_df, df):
    new_row = {'data' : str(df.iloc[-1][0]),
       'dia' : str(df.iloc[-1][1]),
       'seguidores' : str(df.iloc[-1][2]), 
       'seguindo' : str(df.iloc[-1][3]) , 
       'posts' : str(df.iloc[-1][4]) }
    return base_df.append(new_row, ignore_index = True)  

# Junta as linhas de todos os DataFrames das pastas presentes de um usuario
def joinAllDays(user):
    initial_day = '19-02-2021'
    day = (datetime.strptime(initial_day, "%d-%m-%Y") + timedelta(days = 0)).strftime("%d-%m-%Y")
    df_base = pd.read_csv(f'participantes/dados/{day}/{user}.csv')
    i = 1
    exists = True
    while exists:
        try:
            day = (datetime.strptime(initial_day, "%d-%m-%Y") + timedelta(days = i)).strftime("%d-%m-%Y")
            new_df = pd.read_csv(f'participantes/dados/{day}/{user}.csv')
            df_base = addRow(df_base, new_df)
            i += 1
        except:
            exists = False
            print(f'Tabela de {user} completamente atualizada!')
    return df_base

# Unifica os dados de todos os usuarios e cria um .csv para cada um na pasta 'total'
def updateAll(file_name):
    file = open('participantes/usuarios/' + file_name + '.txt')
    user_list = file.read().split()
    for user in user_list:
        df = joinAllDays(user)
        df.to_csv(f'participantes/dados/total/{user}.csv', index = False)
    file.close()
    
# Executa a função
updateAll('nomes')

Tabela de kercardoso completamente atualizada!
Tabela de juliette.freire completamente atualizada!
Tabela de arthurpicoli completamente atualizada!
Tabela de afiune_caio completamente atualizada!
Tabela de joaolpedrosa completamente atualizada!
Tabela de bilaraujjo completamente atualizada!
Tabela de carladiaz completamente atualizada!
Tabela de karolconka completamente atualizada!
Tabela de camilladelucas completamente atualizada!
Tabela de pocah completamente atualizada!
Tabela de negodioficial completamente atualizada!
Tabela de lucaskokapenteado completamente atualizada!
Tabela de irodolffo completamente atualizada!
Tabela de lumena.aleluia completamente atualizada!
Tabela de gilnogueiraofc completamente atualizada!
Tabela de viihtube completamente atualizada!
Tabela de sarah_andrade completamente atualizada!
Tabela de projota completamente atualizada!
Tabela de fiuk completamente atualizada!
Tabela de thaisfbraz completamente atualizada!

In [270]:
# def updateAllrows(file_name):
#     file = open('participantes/usuarios/' + file_name + '.txt')
#     user_list = file.read().split()
#     for user in user_list:
#         df = pd.read_csv(f'participantes/dados/21-02-2021/{user}.csv')
#         df = df.drop([13])
#         df.to_csv(f'participantes/dados/21-02-2021/{user}.csv', index = False)
#     file.close()
    
# updateAllrows('nomes')

In [32]:
pd.read_csv('participantes/dados/total/sarah_andrade.csv')

          data  dia  seguidores  seguindo  posts
0   2021-02-04  Qui     1829935      1155    134
1   2021-02-06  Sab     2133264      1160    141
2   2021-02-07  Dom     2568813      1162    145
3   2021-02-08  Seg     3305770      1171    151
4   2021-02-09  Ter     3799904      1174    157
5   2021-02-10  Qua     4312582      1176    163
6   2021-02-11  Qui     4563719      1178    166
7   2021-02-12  Sex     4761916      1180    169
8   2021-02-13  Sab     4943878      1189    172
9   2021-02-14  Dom     5154671      1191    175
10  2021-02-15  Seg     5429713      1192    183
11  2021-02-16  Ter     5768433      1192    184
12  2021-02-17  Qua     6203691      1199    186
13  2021-02-18  Qui     6402923      1202    188
14  2021-02-19  Sex     6706445      1200    192
15  2021-02-20  Sab     6885529      1199    193
16  2021-02-21  Dom     7141881      1202    197
17  2021-02-21  Dom     7141881      1202    197
18  2021-02-23  Ter     7947099      1215    208
19  2021-02-24  Qua     8231926      1215    210
20  2021-02-25  Qui     8398383      1216    211
21  2021-02-26  Sex     8519673      1216    213
22  2021-02-27  Sab     8631961      1216    215
23  2021-02-28  Dom     8740530      1216    217
24  2021-03-01  Seg     8855752      1216    220
25  2021-03-03  Qua     8869819      1219    220
26  2021-03-03  Qua     8869819      1219    220
27  2021-03-05  Sex     8926719      1223    225
28  2021-03-06  Sab     8766250      1222    227
29  2021-03-06  Sab     8766250      1222    227
30  2021-03-08  Seg     8664033      1218    231
31  2021-03-08  Seg     8664033      1218    231
32  2021-03-10  Qua     8403913      1221    236
33  2021-03-11  Qui     8021488      1224    239
34  2021-03-11  Qui     8021488      1224    239
35  2021-03-11  Qui     8021488      1224    239
36  2021-03-14  Dom     7854001      1227    248
37  2021-03-15  Seg     7871979      1227    251
38  2021-03-15  Seg     7871979      1227    251
39  2021-03-15  Seg     7871979      1227    251
40  2021-03-18  Qui     7883704      1229    259
41  2021-03-19  Sex     7864335      1228    262
42  2021-03-19  Sex     7864335      1228    262
43  2021-03-19  Sex     7864335      1228    262
44  2021-03-19  Sex     7864335      1228    262
45  2021-03-23  Ter     7614073      1226    273